/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hibritSifrelemeBilgisayardaGüvenliDepolama;

import com.sun.corba.se.impl.protocol.giopmsgheaders.Message;
import java.net.PasswordAuthentication;
import java.util.Properties;
import java.util.Random;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import sun.rmi.transport.Transport;

/**
 *
 * @author onurs
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnTemizle = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAd = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSoyad = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMail = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtData = new javax.swing.JTextPane();
        btnKaydet = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtKarakter = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        resim = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 0));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AD");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 20, 50, 40);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Soyad");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 60, 35, 16);

        btnTemizle.setText("TEMİZLE");
        btnTemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemizleActionPerformed(evt);
            }
        });
        getContentPane().add(btnTemizle);
        btnTemizle.setBounds(520, 320, 119, 53);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("e posta adresiniz");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(42, 95, 97, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("kaydetmek istenen veri");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 170, 131, 16);

        jScrollPane1.setViewportView(txtAd);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(460, 30, 260, 30);

        jScrollPane3.setViewportView(txtSoyad);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(460, 70, 260, 30);

        jScrollPane2.setViewportView(txtMail);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(460, 110, 260, 30);

        jScrollPane4.setViewportView(txtData);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(370, 160, 421, 30);

        btnKaydet.setText("KAYDET");
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetActionPerformed(evt);
            }
        });
        getContentPane().add(btnKaydet);
        btnKaydet.setBounds(184, 319, 144, 53);

        jScrollPane5.setViewportView(txtKarakter);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(460, 220, 106, 24);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("şifre belirleme karakteri");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 230, 136, 16);

        resim.setIcon(new javax.swing.ImageIcon("D:\\masaüstü\\bg.jpg")); // NOI18N
        getContentPane().add(resim);
        resim.setBounds(0, -170, 940, 860);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
        
        Random random = new Random();

        // Parolanın uzunluğunu belirleyin (örneğin, 8 karakter)
        int passwordLength = 8;   //txtuzunluk

        // Parola için bir karakter dizisi oluşturun
        char[] password = new char[passwordLength];

        // Parola için rastgele karakterler oluşturun
        for (int i = 0; i < passwordLength; i++) {
            // Bir karakter oluşturmak için, rastgele bir sayı üretin ve
            // bu sayıyı 'a' ile 'z' arasındaki ASCII değerlerine göre dönüştürün
            password[i] = (char) ('a' + random.nextInt(26));
        }

        String  sifre = (txtKarakter.getText()+new String(password));
        String data  = txtData.getText();
        password pas = new password(sifre);
       
        Properties pro = new Properties();

        String kullaniciadi = "Merhaba " + txtAd.getText() + " " + txtSoyad.getText();
        UIManager.put("OptionPane.okButtonText", "Gönder");
        UIManager.put("OptionPane.cancelButtonText", "İptal");
        String mesajj = "Merhaba " + txtAd.getText() + " " + txtSoyad.getText() + " Şifreniz  :  " +txtKarakter.getText()+new String(password);
        String mailadres = txtMail.getText();

        pro.put("mail.smtp.host", "smtp.gmail.com");
        pro.put("mail.smtp.socketFactory.port", "466");
        pro.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        pro.put("mail.smtp.auth", "true");
        pro.put("mail.smtp.port", "466");

        Session session = Session.getDefaultInstance(pro,
                new javax.mail.Authenticator() {

                    protected javax.mail.PasswordAuthentication getPasswordAuthentication() {

                        return new javax.mail.PasswordAuthentication("onursonmez3437@gmail.com", "zzfdpjozbksfesgp");

                    }

                });
        
        
         // sayfa gecis  
        
        NewJFrame1 sayfa2 = new NewJFrame1(sifre,data);
        setVisible(false);
        sayfa2.setVisible(true);

        try {
            javax.mail.Message mesaj = new MimeMessage(session);
            mesaj.setFrom(new InternetAddress("onursonmez3437@gmail.com"));

            mesaj.setRecipients(javax.mail.Message.RecipientType.TO, InternetAddress.parse(mailadres));
            mesaj.setSubject(kullaniciadi);
            mesaj.setText(kullaniciadi + "\n" + mesajj);
            javax.mail.Transport.send(mesaj);
            JOptionPane.showMessageDialog(null, "Mesajınız gönderildi.");
        } catch (MessagingException eex) {
            JOptionPane.showMessageDialog(null, "Hata Meydana Geldi.\n" + "Hata kodu  : " + eex.toString());
        }


    }//GEN-LAST:event_btnKaydetActionPerformed

    private void btnTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemizleActionPerformed
        txtAd.setText(null);
        txtSoyad.setText(null);
        txtData.setText(null);
        txtKarakter.setText(null);
        txtMail.setText(null);
    }//GEN-LAST:event_btnTemizleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKaydet;
    private javax.swing.JButton btnTemizle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel resim;
    private javax.swing.JTextPane txtAd;
    private javax.swing.JTextPane txtData;
    private javax.swing.JTextPane txtKarakter;
    private javax.swing.JTextPane txtMail;
    private javax.swing.JTextPane txtSoyad;
    // End of variables declaration//GEN-END:variables
}
